spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.93.33.180:3306/class_lei?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=GMT%2b8
    username: class_lei
    password: 123456
  redis:
    database: 0
    host: 47.93.33.180         # Redis?????
    port: 6379              # Redis???????
    password:               # Redis?????????????
    pool:
      max-active: 200       # ????????????????????
      max-idle: 10          # ???????????
      max-wait: -1          # ???????????????????????
      min-idle: 0           # ???????????
  rabbitmq:
    host: 47.93.33.180
    port: 5672
    username: guest
    password: guest
    publisher-confirm-type: correlated
    publisher-returns: true


minio:
  endpoint: http://47.93.33.180:9000 #MinIO??????
  bucketName: taskmanagement #?????
  accessKey: admin #???key
  secretKey: 12345678 #?????
server:
  port: 8081
  error:
    include-message: always
    include-exception: true
sjj:
  jwt:
    header: Authorization
    expire: 604800 #7天
    secret: ji8n3439n439n43ld9ne9343fdfer49h

